sonar.verbose=true Untitled-1 .
sonar.verbose=true
sonar.organization=raveena-organization
sonar.projectKey=raveena-organization_ttweet-trend
sonar.projectName=ttweet-trend
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources =.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml